import { Pet, Species } from '../types';

export const SPECIES_CONFIG: Record<
  Species,
  { label: string; emoji: string; defaultBreeds: string[] }
> = {
  dog: {
    label: 'Dog',
    emoji: '\uD83D\uDC15',
    defaultBreeds: [
      'Golden Retriever',
      'Labrador Retriever',
      'German Shepherd',
      'Bulldog',
      'Poodle',
      'Beagle',
      'Husky',
      'Dachshund',
    ],
  },
  cat: {
    label: 'Cat',
    emoji: '\uD83D\uDC08',
    defaultBreeds: [
      'Persian',
      'Siamese',
      'Maine Coon',
      'Ragdoll',
      'Bengal',
      'British Shorthair',
      'Abyssinian',
      'Sphynx',
    ],
  },
  bird: {
    label: 'Bird',
    emoji: '\uD83D\uDC26',
    defaultBreeds: [
      'Parrot',
      'Canary',
      'Cockatiel',
      'Budgerigar',
      'Finch',
      'Lovebird',
      'Macaw',
      'Cockatoo',
    ],
  },
  rabbit: {
    label: 'Rabbit',
    emoji: '\uD83D\uDC07',
    defaultBreeds: [
      'Holland Lop',
      'Mini Rex',
      'Netherland Dwarf',
      'Lionhead',
      'Flemish Giant',
      'English Angora',
      'Dutch',
      'Mini Lop',
    ],
  },
  fish: {
    label: 'Fish',
    emoji: '\uD83D\uDC20',
    defaultBreeds: [
      'Goldfish',
      'Betta',
      'Guppy',
      'Neon Tetra',
      'Angelfish',
      'Oscar',
      'Clownfish',
      'Molly',
    ],
  },
  reptile: {
    label: 'Reptile',
    emoji: '\uD83E\uDD8E',
    defaultBreeds: [
      'Gecko',
      'Bearded Dragon',
      'Ball Python',
      'Corn Snake',
      'Chameleon',
      'Blue-Tongued Skink',
      'Iguana',
      'Tortoise',
    ],
  },
  other: {
    label: 'Other',
    emoji: '\uD83D\uDC3E',
    defaultBreeds: [],
  },
};

export const AVATAR_COLORS: string[] = [
  '#FF6B6B',
  '#4ECDC4',
  '#45B7D1',
  '#96CEB4',
  '#FFEAA7',
  '#DDA0DD',
  '#98D8C8',
  '#F7DC6F',
];

export const MOCK_PETS: Pet[] = [
  {
    id: '1',
    name: 'Buddy',
    species: 'dog',
    breed: 'Golden Retriever',
    age: 4,
    notes: 'Loves playing fetch in the park. Very friendly with other dogs.',
    avatarColor: '#FF6B6B',
    createdAt: '2025-08-15T10:30:00.000Z',
    updatedAt: '2025-12-01T14:20:00.000Z',
  },
  {
    id: '2',
    name: 'Whiskers',
    species: 'cat',
    breed: 'Siamese',
    age: 3,
    notes: 'Indoor cat. Prefers wet food over dry kibble.',
    avatarColor: '#4ECDC4',
    createdAt: '2025-09-20T09:00:00.000Z',
    updatedAt: '2026-01-10T11:45:00.000Z',
  },
  {
    id: '3',
    name: 'Kiwi',
    species: 'bird',
    breed: 'Cockatiel',
    age: 2,
    notes: 'Can whistle three different songs. Gets startled by loud noises.',
    avatarColor: '#45B7D1',
    createdAt: '2025-11-05T16:15:00.000Z',
    updatedAt: '2026-02-18T08:30:00.000Z',
  },
  {
    id: '4',
    name: 'Cinnamon',
    species: 'rabbit',
    breed: 'Holland Lop',
    age: 1,
    notes: 'Litter-trained. Enjoys fresh cilantro and timothy hay.',
    avatarColor: '#96CEB4',
    createdAt: '2026-01-12T13:00:00.000Z',
    updatedAt: '2026-03-01T10:00:00.000Z',
  },
  {
    id: '5',
    name: 'Draco',
    species: 'reptile',
    breed: 'Bearded Dragon',
    age: 5,
    notes:
      'Needs UVB lighting on a 12-hour cycle. Eats crickets and leafy greens.',
    avatarColor: '#DDA0DD',
    createdAt: '2025-06-30T08:45:00.000Z',
    updatedAt: '2026-02-25T17:10:00.000Z',
  },
];
